// The agency keys, arranged the way they are actually worked.
//
// connectionRegistry.ts already declares every credential, but it declares them
// by INTEGRATION, which is the right shape for "what went dark" and the wrong
// shape for "I have eight keys to paste in". This file is the second view: the
// same keys, grouped by what they switch on, and marked with how each one is
// obtained. A key is pasted from a vendor dashboard, generated by us, or locked.
//
// The catalogue is asserted against the registry in the tests, so a credential
// added to one and forgotten in the other fails the build rather than quietly
// vanishing from the screen an operator relies on.

import { CONNECTIONS } from "./connectionRegistry";
import type { AgencySecretRow } from "./secretsApi";

export interface KeyGroup {
  id: string;
  label: string;
  /** What this group of keys buys you, in one line. */
  blurb: string;
}

export const KEY_GROUPS: KeyGroup[] = [
  { id: "ads", label: "Paid ads", blurb: "Spend, impressions and creative for every client ad account." },
  { id: "leads", label: "Lead sync", blurb: "How leads and messages reach the app from GoHighLevel." },
  { id: "coldcall", label: "Cold calling", blurb: "Hauck Marketing's own sub-account, where your meetings get booked." },
  { id: "calendars", label: "Calendars", blurb: "Two-way sync onto each client's real Google Calendar." },
  { id: "email", label: "Email", blurb: "Internal notification email relayed from GoHighLevel workflows." },
  { id: "drive", label: "Drive and assets", blurb: "The Assets hub, the SOP Hub, and each new client's folder." },
  { id: "push", label: "Push notifications", blurb: "Browser alerts on a new lead. Entirely ours, no vendor." },
  { id: "signin", label: "Sign-in", blurb: "The shared password and the signed session cookie." },
  { id: "crons", label: "Scheduled jobs", blurb: "The health watchdog and the nightly ad spend refresh." },
  { id: "buildlab", label: "Build Lab", blurb: "Reads the build plans out of the repo." },
  { id: "testmode", label: "Made Better", blurb: "Made Better Landscaping Co's sub-account. A real client: it was the test account until 2026-08-09, so these var names still say TEST." },
  { id: "platform", label: "Platform", blurb: "The keys this page runs on. Read-only here, on purpose." },
  { id: "unused", label: "Not in use", blurb: "Declared, but you do not do this work. Left visible so nothing is a mystery." },
];

/** How a key is obtained, which decides what control it gets. */
export type KeyEntry =
  /** Pasted from a vendor dashboard. */
  | "paste"
  /** Invented by us. Gets a Generate button. */
  | "generate"
  /** Shown, never editable here. See LOCK_REASON. */
  | "locked";

export type Generator = "hex32" | "vapid";

export interface AgencyKeyDef {
  name: string;
  group: string;
  entry: KeyEntry;
  /** Where to find it, or what it is. */
  help: string;
  /** The consequence of changing it. Printed before the value is replaced. */
  warning?: string;
  /** Only for entry: "generate". */
  generator?: Generator;
  /**
   * Generated alongside another key, so the UI offers one button for the pair
   * rather than two that would produce a mismatched public and private half.
   */
  pairedWith?: string;
}

/**
 * Why a key cannot be edited here.
 *
 * The first three grant this page its own power. A screen that can rewrite the
 * credentials it authenticates with can lock you out of itself permanently, or
 * quietly widen its own access, and neither failure announces itself. They stay
 * a command-line job. The Supabase three are read-only for a different reason:
 * a new client needs no input there at all, so an editable box would imply work
 * that does not exist.
 */
export const LOCK_REASON: Record<string, string> = {
  CF_DEPLOY_TOKEN: "Grants this page its deploy power. Editable here, it could revoke its own access.",
  DOPPLER_TOKEN: "Grants this page its read of Doppler. Same reason.",
  DOPPLER_WRITE_TOKEN: "Grants this page its write to Doppler. Same reason.",
  CLOUDFLARE_ACCOUNT_ID: "Names the account this app deploys into. Changing it here would point Apply at nothing.",
  CF_PAGES_PROJECT: "Names the Pages project. Same reason.",
  SUPABASE_URL: "Set once. A new client needs nothing here.",
  SUPABASE_SERVICE_ROLE_KEY: "Set once. A new client needs nothing here.",
  SUPABASE_ANON_KEY: "Set once. A new client needs nothing here.",
};

export const AGENCY_KEYS: AgencyKeyDef[] = [
  // --- Paid ads -------------------------------------------------------------
  {
    name: "META_SYSTEM_USER_TOKEN",
    group: "ads",
    entry: "paste",
    help: "Meta Business Settings, System Users. One token covers every client ad account.",
    warning: "System User tokens do not expire on a timer, they die when permissions change.",
  },
  {
    name: "META_AD_ACCOUNT_ID",
    group: "ads",
    entry: "paste",
    help: "Single-tenant fallback only. Each client's real ad account lives on their own row.",
  },

  // --- Lead sync ------------------------------------------------------------
  {
    name: "WEBHOOK_SECRET",
    group: "leads",
    entry: "generate",
    generator: "hex32",
    help: "Shared with the GoHighLevel workflow that posts new leads and messages to us.",
    warning: "Both sides must change together. A rotated secret makes GHL's calls fail silently, so the app just looks stale.",
  },
  {
    name: "SHEETS_SYNC_TOKEN",
    group: "leads",
    entry: "generate",
    generator: "hex32",
    help: "Read by the Apps Script inside each client's Google Sheet lead tracker, as its API_TOKEN script property.",
    warning: "Rotating this stops every client sheet at once, and Apps Script only emails the sheet's owner when it fails. Update each sheet's script property in the same sitting.",
  },
  {
    name: "GHL_TOKEN",
    group: "leads",
    entry: "paste",
    help: "Single-tenant fallback for the client app. Admin write paths never use it.",
  },
  { name: "GHL_LOCATION_ID", group: "leads", entry: "paste", help: "The matching sub-account id." },
  {
    name: "GHL_COMPANY_ID",
    group: "leads",
    entry: "paste",
    help: "Only needed to provision a new GoHighLevel user when adding staff.",
  },
  {
    name: "GHL_APP_CLIENT_ID",
    group: "leads",
    entry: "paste",
    help: "The private Marketplace app the agency installs across every sub-account, so reporting arrives without a workflow being built by hand.",
  },
  {
    name: "GHL_APP_CLIENT_SECRET",
    group: "leads",
    entry: "paste",
    help: "Generated alongside the client id and shown once.",
    warning: "Lost secrets cannot be read back. Recovering one means generating a new key pair and reinstalling the app.",
  },
  {
    name: "GHL_APP_ID",
    group: "leads",
    entry: "paste",
    help: "Only used to build the install link on the Connection screen.",
  },

  {
    name: "CALENDAR_CRON_SECRET",
    group: "crons",
    entry: "generate",
    generator: "hex32",
    help: "Lets the scheduler push a client's busy time into the calendar their customers book into, every fifteen minutes.",
    warning: "Must differ from the other cron secrets. One value shared between them means one leak opens all three.",
  },

  // --- Cold calling ---------------------------------------------------------
  {
    name: "AGENCY_GHL_LOCATION_ID",
    group: "coldcall",
    entry: "paste",
    help: "The Hauck Marketing sub-account, not a client's.",
  },
  {
    name: "AGENCY_GHL_TOKEN",
    group: "coldcall",
    entry: "paste",
    help: "A Private Integration Token created inside the Hauck Marketing sub-account.",
  },
  {
    name: "AGENCY_GHL_USER_ID",
    group: "coldcall",
    entry: "paste",
    help: "Who a callback task is assigned to. Defaults to you.",
  },

  // --- Calendars ------------------------------------------------------------
  { name: "COMPOSIO_API_KEY", group: "calendars", entry: "paste", help: "From the Composio dashboard." },
  {
    name: "COMPOSIO_GCAL_AUTH_CONFIG_ID",
    group: "calendars",
    entry: "paste",
    help: "The Google Calendar auth config. Each client then consents through it themselves.",
  },

  // --- Email ----------------------------------------------------------------
  { name: "RESEND_API_KEY", group: "email", entry: "paste", help: "A send-only restricted key from Resend." },
  {
    name: "NOTIFY_FROM",
    group: "email",
    entry: "paste",
    help: "The locked From address. A caller cannot override it.",
  },

  // --- Drive ----------------------------------------------------------------
  { name: "GOOGLE_OAUTH_CLIENT_ID", group: "drive", entry: "paste", help: "Google Cloud console, OAuth credentials." },
  { name: "GOOGLE_OAUTH_CLIENT_SECRET", group: "drive", entry: "paste", help: "The matching secret." },
  {
    name: "GOOGLE_OAUTH_REDIRECT",
    group: "drive",
    entry: "paste",
    help: "Defaults to the production callback when unset.",
  },
  {
    name: "CLIENT_DRIVE_ROOT_FOLDER_ID",
    group: "drive",
    entry: "paste",
    help: "The folder a new client's own folder is created inside. Unset means creating a client skips the folder.",
  },
  {
    name: "SOP_DRIVE_FOLDER_ID",
    group: "drive",
    entry: "paste",
    help: "The 'SOPs Templates' folder. Unset renders a setup state rather than reading the wrong folder.",
  },

  // --- Push -----------------------------------------------------------------
  {
    name: "VAPID_PUBLIC_KEY",
    group: "push",
    entry: "generate",
    generator: "vapid",
    pairedWith: "VAPID_PRIVATE_KEY",
    help: "Generated as a pair. Browsers use the public half to identify us.",
    warning: "Rotating these invalidates every existing subscription. Every device has to re-subscribe, and anyone who dismissed the prompt has no way back in.",
  },
  {
    name: "VAPID_PRIVATE_KEY",
    group: "push",
    entry: "generate",
    generator: "vapid",
    pairedWith: "VAPID_PUBLIC_KEY",
    help: "The private half. Generated with the public one, never separately.",
    warning: "Rotating these invalidates every existing subscription.",
  },

  // --- Sign-in --------------------------------------------------------------
  { name: "APP_PASSWORD", group: "signin", entry: "paste", help: "The shared password for the client app." },
  {
    name: "SESSION_SECRET",
    group: "signin",
    entry: "generate",
    generator: "hex32",
    help: "Signs the session cookie. Nobody types this, so it should be random.",
    warning: "Changing this signs every user out at once, clients included.",
  },
  { name: "TEST_APP_PASSWORD", group: "signin", entry: "paste", help: "The shared password for Made Better Landscaping Co's sign-in." },

  // --- Crons ----------------------------------------------------------------
  {
    name: "HEALTH_CRON_SECRET",
    group: "crons",
    entry: "generate",
    generator: "hex32",
    help: "Buys the caller one read-only health snapshot and no admin power at all.",
    warning: "Also paste it into the Worker: wrangler secret put HEALTH_CRON_SECRET in workers/health-cron. Set in only one place and the checks silently stop.",
  },
  {
    name: "ADS_CRON_SECRET",
    group: "crons",
    entry: "generate",
    generator: "hex32",
    help: "Triggers the nightly ad spend refresh. A write, unlike the health one.",
    warning: "Also paste it into workers/ads-cron. It must NOT match HEALTH_CRON_SECRET: that one buys a read, this one triggers a write.",
  },

  // --- Build Lab ------------------------------------------------------------
  {
    name: "GITHUB_TOKEN",
    group: "buildlab",
    entry: "paste",
    help: "Contents-read is enough.",
    warning: "The only key here with a hard expiry date on it.",
  },
  { name: "GITHUB_REPO", group: "buildlab", entry: "paste", help: "owner/repo. Defaults to this one." },

  // --- Made Better Landscaping Co --------------------------------------------
  { name: "TEST_GHL_TOKEN", group: "testmode", entry: "paste", help: "A token inside Made Better Landscaping Co's sub-account." },
  { name: "TEST_GHL_LOCATION_ID", group: "testmode", entry: "paste", help: "Made Better Landscaping Co's location id." },

  // --- Platform (locked) ----------------------------------------------------
  { name: "CF_DEPLOY_TOKEN", group: "platform", entry: "locked", help: "Pages:Edit on this project only. What makes Apply work." },
  { name: "CLOUDFLARE_ACCOUNT_ID", group: "platform", entry: "locked", help: "The account this app deploys into." },
  { name: "CF_PAGES_PROJECT", group: "platform", entry: "locked", help: "The Pages project name." },
  { name: "DOPPLER_TOKEN", group: "platform", entry: "locked", help: "Read-only. Cannot live in Doppler itself." },
  { name: "DOPPLER_WRITE_TOKEN", group: "platform", entry: "locked", help: "What turns editing on at all." },
  { name: "SUPABASE_URL", group: "platform", entry: "locked", help: "The database. Set once." },
  { name: "SUPABASE_SERVICE_ROLE_KEY", group: "platform", entry: "locked", help: "Server-only. Never reaches the browser." },
  { name: "SUPABASE_ANON_KEY", group: "platform", entry: "locked", help: "Browser-safe, for the Realtime chat socket." },

  // --- Not in use -----------------------------------------------------------
  { name: "GA4_SA_JSON", group: "unused", entry: "paste", help: "Website analytics. You do not do this work." },
  { name: "GA4_PROPERTY_ID", group: "unused", entry: "paste", help: "Website analytics." },
  { name: "GOOGLE_PLACES_API_KEY", group: "unused", entry: "paste", help: "The review rating hero. You do not do this work." },
  { name: "GOOGLE_PLACE_ID", group: "unused", entry: "paste", help: "The business listing reviews are pulled from." },
];

/** Keys the write endpoint must refuse, whatever the UI does. */
export const LOCKED_KEYS: string[] = AGENCY_KEYS.filter((k) => k.entry === "locked").map((k) => k.name);

export function isLocked(name: string): boolean {
  return LOCKED_KEYS.includes(name);
}

export function keyDef(name: string): AgencyKeyDef | undefined {
  return AGENCY_KEYS.find((k) => k.name === name);
}

/** Every Cloudflare-homed credential the registry declares, deduplicated. */
export function registryKeyNames(): string[] {
  const names = new Set<string>();
  for (const def of CONNECTIONS) {
    for (const c of def.credentials) {
      if (c.home === "cloudflare") names.add(c.name);
    }
  }
  return [...names].sort();
}

// --- Status ------------------------------------------------------------------

/**
 * What one key is doing right now.
 *
 * `pending` is the state this whole build exists to make visible: Doppler has
 * the new value and the running app does not, which until now was reported as
 * a drift warning and a shell command rather than as a thing you could finish.
 */
export type KeyStatus = "live" | "pending" | "missing";

export function keyStatus(row: AgencySecretRow): KeyStatus {
  if (!row.inDoppler && !row.inRuntime) return "missing";
  // In Doppler but absent from the deploy, or present in both and different:
  // either way the running app is not serving what Doppler says it should.
  if (row.inDoppler && (!row.inRuntime || row.drift === true)) return "pending";
  return "live";
}

export const STATUS_LABEL: Record<KeyStatus, string> = {
  live: "Live",
  pending: "Saved, pending restart",
  missing: "Not set",
};

/** The keys an Apply would actually change. Drives the footer count. */
export function pendingKeys(rows: AgencySecretRow[]): AgencySecretRow[] {
  return rows.filter((r) => keyStatus(r) === "pending");
}

export interface GroupedKeys {
  group: KeyGroup;
  keys: { def: AgencyKeyDef; row: AgencySecretRow | null }[];
}

/**
 * The catalogue joined to live status, in group order.
 *
 * A key the server reports but the catalogue has never heard of still appears,
 * under "Not in use", rather than being dropped: an unknown key on this screen
 * is a prompt to file it, and silently hiding one is how a credential goes
 * missing for a month.
 */
export function groupedKeys(rows: AgencySecretRow[]): GroupedKeys[] {
  const byName = new Map(rows.map((r) => [r.name, r]));
  const known = new Set(AGENCY_KEYS.map((k) => k.name));

  const strays: AgencyKeyDef[] = rows
    .filter((r) => !known.has(r.name))
    .map((r) => ({
      name: r.name,
      group: "unused",
      entry: "paste" as KeyEntry,
      help: "Declared by an integration but not yet filed into a group here.",
    }));

  const all = [...AGENCY_KEYS, ...strays];

  return KEY_GROUPS.map((group) => ({
    group,
    keys: all
      .filter((k) => k.group === group.id)
      .map((def) => ({ def, row: byName.get(def.name) ?? null })),
  })).filter((g) => g.keys.length > 0);
}
