// SOP seed data for the admin SOP Hub. Seeded from the Local Ads School
// classroom (Month 1: Running Ads + The Original Local META Ads Masterclass).
// Each SOP carries its original training video; written step-by-step bodies are
// added as each lesson is processed. Shape is unchanged from the original seed.

export interface Sop {
  slug: string;
  title: string;
  emoji: string;
  desc: string;
  video?: boolean;
  videoUrl?: string;
  body: string;
}
export interface SopCategory {
  key: string;
  name: string;
  emoji: string;
  sops: Sop[];
}

export const SOP_CATEGORIES: SopCategory[] = [
  {
    key: "month-1-running-ads", name: "Month 1: Running Ads", emoji: "🎯",
    sops: [
      { slug: "what-s-inside-running-ads", title: "What's inside Running Ads", emoji: "🎬", desc: "2:10", video: true, videoUrl: "https://www.loom.com/share/5576a50e52ee468f98aacb49a7b6e437",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Month 1: Running Ads).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "campaign-prep-with-co-pilot", title: "Campaign Prep with CO-pilot", emoji: "🎬", desc: "8:29", video: true, videoUrl: "https://www.loom.com/share/5a75b93189fe42e3b578ab7baff7af28",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Month 1: Running Ads).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "the-local-business-offer-playbook", title: "The Local Business Offer Playbook", emoji: "🎬", desc: "1:57", video: true, videoUrl: "https://www.loom.com/share/272abe4e3bf149f39a23deb7f52e4808",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Month 1: Running Ads).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "generating-scripts-hooks-and-headlines", title: "Generating scripts, hooks, and headlines", emoji: "🎬", desc: "7:11", video: true, videoUrl: "https://www.loom.com/share/e23e02d6c9e54f1c9283af8f3aec18ec",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Month 1: Running Ads).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "copywriting-masterclass-for-local-ads", title: "Copywriting masterclass (for local ads)", emoji: "🎬", desc: "2:03", video: true, videoUrl: "https://www.loom.com/share/46f788c425fd46119f3652f1a30ffe43",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Month 1: Running Ads).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "creative-prep-doc-1-video-hooks-and-scripts", title: "Creative Prep doc 1: Video hooks and scripts", emoji: "🎬", desc: "17:17", video: true, videoUrl: "https://www.loom.com/share/c9adcb8e31834b1a84d48094d95e9721",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Month 1: Running Ads).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "creative-prep-doc-2-image-headlines", title: "Creative Prep doc 2: Image headlines", emoji: "🎬", desc: "4:42", video: true, videoUrl: "https://www.loom.com/share/580fd3a471e04d8b9ef327d7c53605f6",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Month 1: Running Ads).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "generating-sora-hooks", title: "Generating SORA Hooks", emoji: "🎬", desc: "11:34", video: true, videoUrl: "https://www.loom.com/share/9b8c83c7116d4091afeadcc8ad95746d",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Month 1: Running Ads).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "image-ad-generation", title: "Image ad Generation", emoji: "🎬", desc: "13:52", video: true, videoUrl: "https://www.loom.com/share/43604180c63c4beaa9dd42734e876288",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Month 1: Running Ads).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "submitting-edits", title: "Submitting Edits", emoji: "🎬", desc: "13:56", video: true, videoUrl: "https://www.loom.com/share/87d5d9278e1a40c3b2e7788815e8ecdc",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Month 1: Running Ads).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "ad-approvals", title: "Ad Approvals", emoji: "🎬", desc: "8:51", video: true, videoUrl: "https://www.loom.com/share/300db6dc408345b191b3882905a9fc2e",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Month 1: Running Ads).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "organising-meta-ad-creatives", title: "Organising META Ad Creatives", emoji: "🎬", desc: "7:49", video: true, videoUrl: "https://www.loom.com/share/6554271eeb2b45f8a43910514a52d04a",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Month 1: Running Ads).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "setting-up-our-ads-full-walkthrough", title: "Setting up our ads (full walkthrough)", emoji: "🎬", desc: "24:14", video: true, videoUrl: "https://www.loom.com/share/e23004b98d9640f2b94fad37fc3d20b1",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Month 1: Running Ads).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "naming-and-setting-up-our-ads", title: "Naming & Setting up our ads", emoji: "🎬", desc: "12:49", video: true, videoUrl: "https://www.loom.com/share/24b1322eb7fb4bb388a570642c62bb57",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Month 1: Running Ads).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "ad-creative-testing-and-diagnosis", title: "Ad Creative Testing & Diagnosis", emoji: "🎬", desc: "19:21", video: true, videoUrl: "https://www.loom.com/share/9463f0f3949e4394892c25d40b4dc145",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Month 1: Running Ads).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "one-campaign-testing-explained", title: "One Campaign Testing Explained", emoji: "🎬", desc: "4:55", video: true, videoUrl: "https://www.loom.com/share/2ed0ab38fb5944358fbe8b84c3c0a276",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Month 1: Running Ads).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "triad-testing-explained", title: "Triad Testing Explained", emoji: "🎬", desc: "6:05", video: true, videoUrl: "https://www.loom.com/share/3461fd5baf5e4905b4f1e944c0c8c98c",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Month 1: Running Ads).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "testing-rules", title: "Testing Rules", emoji: "🎬", desc: "3:16", video: true, videoUrl: "https://www.loom.com/share/7dcf59c0ecdb425a8fce770c5a5612d0",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Month 1: Running Ads).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
    ],
  },
  {
    key: "meta-ads-101", name: "META Ads 101", emoji: "🧠",
    sops: [
      { slug: "why-meta-ads", title: "Why META Ads?", emoji: "🎬", desc: "7:53", video: true, videoUrl: "https://www.loom.com/share/6c77347a20804f148844e3090afb6ff7",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (META Ads 101).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "why-take-this-course", title: "Why take this course?", emoji: "🎬", desc: "4:20", video: true, videoUrl: "https://www.loom.com/share/35b86a0d06ef4862864f0244ec08046a",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (META Ads 101).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "who-is-this-for", title: "Who is this for?", emoji: "🎬", desc: "2:45", video: true, videoUrl: "https://www.loom.com/share/7a613f13b08045fc958961c504f2012e",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (META Ads 101).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "limiting-beliefs", title: "Limiting beliefs", emoji: "🎬", desc: "6:38", video: true, videoUrl: "https://www.loom.com/share/b33600a86d1c462eb533abcef080694b",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (META Ads 101).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "module-overview", title: "Module overview", emoji: "🎬", desc: "6:48", video: true, videoUrl: "https://www.loom.com/share/cca8cb452d0345228af0db26b25290d1",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (META Ads 101).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
    ],
  },
  {
    key: "module-1-foundations-and-strategy", name: "Module 1 - Foundations & Strategy", emoji: "🧱",
    sops: [
      { slug: "how-clicks-turn-into-customers", title: "How clicks turn into customers", emoji: "🎬", desc: "10:59", video: true, videoUrl: "https://www.loom.com/share/7f6f9ab78fcd4a8d972f5fdc7eb8f987",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 1 - Foundations & Strategy).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "andomeda-how-the-algorithm-works", title: "Andomeda - How the algorithm works", emoji: "🎬", desc: "10:41", video: true, videoUrl: "https://www.loom.com/share/e74d47078ee74bea804bd341255b730b",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 1 - Foundations & Strategy).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "pixels-explained", title: "Pixels explained", emoji: "🎬", desc: "2:32", video: true, videoUrl: "https://www.loom.com/share/40cb682944084a5c872001b40982bf65",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 1 - Foundations & Strategy).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "the-basics-of-advertising-why-people-buy", title: "The basics of advertising (Why people buy)", emoji: "🎬", desc: "14:15", video: true, videoUrl: "https://www.loom.com/share/b25f11530ecc43ccb77fe403a3d5931d",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 1 - Foundations & Strategy).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "the-anatomy-of-attention-p-e-r-f-o-r-m", title: "The anatomy of attention (P.E.R.F.O.R.M)", emoji: "🎬", desc: "14:23", video: true, videoUrl: "https://www.loom.com/share/18ca2ecc8f3d473f90d5707076d54d76",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 1 - Foundations & Strategy).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "p-e-r-f-o-r-m-in-action-example", title: "P.E.R.F.O.R.M in Action (example)", emoji: "🎬", desc: "3:26", video: true, videoUrl: "https://www.loom.com/share/09725374b06446af8039df29e9f53ae0",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 1 - Foundations & Strategy).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "powerful-offers", title: "Powerful Offers", emoji: "🎬", desc: "16:55", video: true, videoUrl: "https://www.loom.com/share/d0b5638daf6b44c3a14c36b8504df181",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 1 - Foundations & Strategy).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "what-is-a-funnel", title: "What is a funnel?", emoji: "🎬", desc: "8:29", video: true, videoUrl: "https://www.loom.com/share/f09411e627604b9ab625a06d1eabbdd4",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 1 - Foundations & Strategy).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "why-do-we-test", title: "Why do we test?", emoji: "🎬", desc: "6:23", video: true, videoUrl: "https://www.loom.com/share/5829cf83ae7141babd310d66b2b1e1b8",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 1 - Foundations & Strategy).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
    ],
  },
  {
    key: "module-2-understanding-the-meta-platform", name: "Module 2 - Understanding the META Platform", emoji: "🏗️",
    sops: [
      { slug: "how-we-run-meta-ads-business-portfolio-overview", title: "How we run META ads (business portfolio overview)", emoji: "🎬", desc: "11:27", video: true, videoUrl: "https://www.loom.com/share/df55ddf6838d44518212cd81e25abab2",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 2 - Understanding the META Platform).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "accessing-or-sharing-account-access-with-others", title: "Accessing or sharing account access with others", emoji: "🎬", desc: "4:58", video: true, videoUrl: "https://www.loom.com/share/960a824cc38b4e88922747176cebc390",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 2 - Understanding the META Platform).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "ads-manager-walkthrough", title: "Ads manager walkthrough", emoji: "🎬", desc: "30:33", video: true, videoUrl: "https://www.loom.com/share/7f1410b882e1499e880d045c18bf4674",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 2 - Understanding the META Platform).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "tracking-and-pixels", title: "Tracking & Pixels", emoji: "🎬", desc: "13:30", video: true, videoUrl: "https://www.loom.com/share/a16c3ffa2a5c4aa0825bda1ec24f9eda",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 2 - Understanding the META Platform).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "meta-audiences", title: "META Audiences", emoji: "🎬", desc: "19:19", video: true, videoUrl: "https://www.loom.com/share/82477e2316df412c9bbf188313a93244",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 2 - Understanding the META Platform).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "lookalike-audiences-are-they-worth-it", title: "Lookalike audiences (are they worth it?)", emoji: "🎬", desc: "4:38", video: true, videoUrl: "https://www.loom.com/share/e8651039b87d42369b48b45e52cb55b2",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 2 - Understanding the META Platform).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "setting-locations-location-selection-guide", title: "Setting locations (location selection guide)", emoji: "🎬", desc: "8:36", video: true, videoUrl: "https://www.loom.com/share/a27cf53855e9429f98bb0c4581e31d63",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 2 - Understanding the META Platform).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "advantage-explained", title: "Advantage + Explained", emoji: "🎬", desc: "17:02", video: true, videoUrl: "https://www.loom.com/share/33226aafd4fe4865896635745b56d700",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 2 - Understanding the META Platform).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "meta-lingo-explained", title: "META Lingo explained", emoji: "🎬", desc: "1:16", video: true, videoUrl: "https://www.loom.com/share/1845d289bf5a4bd6a728ce5ea4da7bb8",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 2 - Understanding the META Platform).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "understanding-budgets", title: "Understanding Budgets", emoji: "🎬", desc: "3:53", video: true, videoUrl: "https://www.loom.com/share/cb118ed7a8ab4594a7fcf2a3ad95789e",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 2 - Understanding the META Platform).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "understanding-ad-breakdowns", title: "Understanding ad breakdowns", emoji: "🎬", desc: "4:10", video: true, videoUrl: "https://www.loom.com/share/ea7b2ad415ac4bedbe3b46087ef3d1fc",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 2 - Understanding the META Platform).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "abo-and-cbo-explained", title: "ABO & CBO explained", emoji: "🎬", desc: "3:20", video: true, videoUrl: "https://www.loom.com/share/7b18c59fda7b4cc697d2d9666842c09e",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 2 - Understanding the META Platform).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "campaigns-ad-sets-and-ads-explained", title: "Campaigns, ad sets and ads explained", emoji: "🎬", desc: "5:29", video: true, videoUrl: "https://www.loom.com/share/c4b7f423c4af40fbbe47afc6d802e1b4",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 2 - Understanding the META Platform).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "understanding-ads-manager-performance", title: "Understanding Ads Manager Performance", emoji: "🎬", desc: "6:12", video: true, videoUrl: "https://www.loom.com/share/72ddcda2d57c4731898a70ec13b4bc44",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 2 - Understanding the META Platform).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
    ],
  },
  {
    key: "module-3-campaign-blueprint", name: "Module 3 - Campaign Blueprint", emoji: "🗺️",
    sops: [
      { slug: "campaign-research-phase", title: "Campaign Research Phase", emoji: "🎬", desc: "18:27", video: true, videoUrl: "https://www.loom.com/share/22f557a2c75c4b708c983a0fa2651510",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 3 - Campaign Blueprint).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "generating-hooks", title: "Generating Hooks", emoji: "🎬", desc: "8:19", video: true, videoUrl: "https://www.loom.com/share/6ecb2fc89fb54434960e5c6192e76303",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 3 - Campaign Blueprint).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "important-direct-ads-vs-indirect-ads", title: "Important: Direct Ads Vs Indirect Ads", emoji: "🎬", desc: "5:10", video: true, videoUrl: "https://www.loom.com/share/3bcae49deca54c20a1a0ea934a7e4c7c",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 3 - Campaign Blueprint).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "creating-video-scripts", title: "Creating video scripts", emoji: "🎬", desc: "9:18", video: true, videoUrl: "https://www.loom.com/share/7c28936cfe154f1581fae285411b1df9",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 3 - Campaign Blueprint).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "writing-our-primary-text", title: "Writing our Primary Text", emoji: "🎬", desc: "9:38", video: true, videoUrl: "https://www.loom.com/share/01f9a693dcc74b11b4c531719d86d417",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 3 - Campaign Blueprint).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "writing-headlines", title: "Writing Headlines", emoji: "🎬", desc: "3:20", video: true, videoUrl: "https://www.loom.com/share/17ebe4af18b046cba01913a05e084739",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 3 - Campaign Blueprint).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "competitor-research", title: "Competitor research", emoji: "🎬", desc: "7:36", video: true, videoUrl: "https://www.loom.com/share/367d07a6d374422dba525a62c7660b81",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 3 - Campaign Blueprint).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "asset-collection", title: "Asset Collection", emoji: "🎬", desc: "9:29", video: true, videoUrl: "https://www.loom.com/share/fd98fa0290204a5c9fc7c89a4809c041",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 3 - Campaign Blueprint).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
    ],
  },
  {
    key: "module-4-preparing-your-ad-account", name: "Module 4 - Preparing Your Ad Account", emoji: "🛠️",
    sops: [
      { slug: "why-preparation-matters", title: "Why Preparation Matters", emoji: "🎬", desc: "1:26", video: true, videoUrl: "https://www.loom.com/share/cb95ebbd85f747759d45b5a9ea02deb5",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 4 - Preparing Your Ad Account).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "structuring-campaigns", title: "Structuring Campaigns", emoji: "🎬", desc: "5:01", video: true, videoUrl: "https://www.loom.com/share/b4d0c7090a1b492798b4367d06f83847",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 4 - Preparing Your Ad Account).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "creating-saved-audiences", title: "Creating Saved Audiences", emoji: "🎬", desc: "6:16", video: true, videoUrl: "https://www.loom.com/share/ea8272bc9edf42638e683de8d8c7e625",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 4 - Preparing Your Ad Account).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "organising-your-media-library", title: "Organising Your Media Library", emoji: "🎬", desc: "2:21", video: true, videoUrl: "https://www.loom.com/share/6aa3632fba574ba3a75c9f9c599f3142",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 4 - Preparing Your Ad Account).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "naming-conventions", title: "Naming conventions", emoji: "🎬", desc: "2:11", video: true, videoUrl: "https://www.loom.com/share/196ca8fc851c42c0818c8db48d8ce540",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 4 - Preparing Your Ad Account).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
    ],
  },
  {
    key: "module-5-creative-that-converts", name: "Module 5 - Creative That Converts", emoji: "🎨",
    sops: [
      { slug: "how-to-build-test-and-scale-winning-ad-creatives", title: "How To Build, Test & Scale Winning Ad Creatives", emoji: "🎬", desc: "Training video", video: true, videoUrl: "https://www.loom.com/share/3e2d63f015404edd9941e0995202af89",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 5 - Creative That Converts).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "the-anatomy-of-an-ad", title: "The Anatomy Of An Ad", emoji: "🎬", desc: "4:03", video: true, videoUrl: "https://www.loom.com/share/e7b3f1c67e1349b281d9fdb638c36f7f",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 5 - Creative That Converts).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "forget-perfection-why-ugly-ads-can-work", title: "Forget perfection (why ugly ads can work)", emoji: "🎬", desc: "8:43", video: true, videoUrl: "https://www.loom.com/share/1bb71042f50741bfa69d91039f79ebcc",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 5 - Creative That Converts).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "ad-formats-and-how-to-use-them", title: "Ad Formats & How To Use Them", emoji: "🎬", desc: "8:59", video: true, videoUrl: "https://www.loom.com/share/cc5d79f63f304524bca1a1037f60a8cf",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 5 - Creative That Converts).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "video-ads-basics", title: "Video Ads Basics", emoji: "🎬", desc: "20:39", video: true, videoUrl: "https://www.loom.com/share/a8e2618d379e43f4b4d382dce9f08e38",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 5 - Creative That Converts).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "video-ads-that-worked-and-why", title: "Video Ads That Worked (And Why)", emoji: "🎬", desc: "15:54", video: true, videoUrl: "https://www.loom.com/share/45d5f6d0930b42c6a67d760fbbcdeb81",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 5 - Creative That Converts).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "scripting-video-ads", title: "Scripting Video Ads", emoji: "🎬", desc: "12:50", video: true, videoUrl: "https://www.loom.com/share/5deb1d0834c14200aa1e669f7079dab1",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 5 - Creative That Converts).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "video-editing-tools", title: "Video Editing Tools", emoji: "🎬", desc: "11:22", video: true, videoUrl: "https://www.loom.com/share/106827b8b2d4493d8c0a21c4140c4265",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 5 - Creative That Converts).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "finding-video-editors", title: "Finding Video Editors", emoji: "🎬", desc: "4:15", video: true, videoUrl: "https://www.loom.com/share/15868addf22f443a8705debd43f6c379",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 5 - Creative That Converts).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "image-ad-basics", title: "Image Ad Basics", emoji: "🎬", desc: "8:14", video: true, videoUrl: "https://www.loom.com/share/2a2e89bdd551483bae6f2da6d450c8c0",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 5 - Creative That Converts).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "creating-statics-google-gemini-nano-banana", title: "Creating statics: Google Gemini Nano Banana", emoji: "🎬", desc: "15:59", video: true, videoUrl: "https://www.youtube.com/watch?v=xolIjBO6aNs",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 5 - Creative That Converts).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "creating-statics-canva", title: "Creating Statics: Canva", emoji: "🎬", desc: "19:59", video: true, videoUrl: "https://www.loom.com/share/7050f11f3d5e4528b819993ebd7524f0",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 5 - Creative That Converts).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "text-callout-ads-the-algo-hackers", title: "Text Callout Ads (The Algo Hackers)", emoji: "🎬", desc: "8:07", video: true, videoUrl: "https://www.loom.com/share/a7b828c4194b4b998ded154fe7bb5d98",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 5 - Creative That Converts).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "ugc-ads", title: "UGC Ads", emoji: "🎬", desc: "9:32", video: true, videoUrl: "https://www.loom.com/share/1c1315cc0a6841c88b76878f32120b13",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 5 - Creative That Converts).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
    ],
  },
  {
    key: "module-6-campaign-objectives", name: "Module 6 - Campaign Objectives", emoji: "🚀",
    sops: [
      { slug: "choosing-the-correct-objective", title: "Choosing The Correct Objective", emoji: "🎬", desc: "8:02", video: true, videoUrl: "https://www.loom.com/share/22fb474912f349bdb16652367eed3eb5",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 6 - Campaign Objectives).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "lead-forms-objective", title: "Lead Forms Objective", emoji: "🎬", desc: "5:17", video: true, videoUrl: "https://www.loom.com/share/19b5ca6b5c504df2ba5b6ee70f72ee72",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 6 - Campaign Objectives).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "website-conversions-objective", title: "Website Conversions Objective", emoji: "🎬", desc: "7:20", video: true, videoUrl: "https://www.loom.com/share/0968745c4d2c4a21a1dcd5da6f08cfa8",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 6 - Campaign Objectives).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "messenger-ads-objective", title: "Messenger Ads Objective", emoji: "🎬", desc: "5:57", video: true, videoUrl: "https://www.loom.com/share/6c58432aa7524c92987d3cae287738df",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 6 - Campaign Objectives).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
    ],
  },
  {
    key: "module-7-funnels-and-destinations", name: "Module 7 - Funnels & Destinations", emoji: "📱",
    sops: [
      { slug: "lead-forms-full-breakdown", title: "Lead Forms - Full Breakdown", emoji: "🎬", desc: "18:03", video: true, videoUrl: "https://www.loom.com/share/4556c6f1ae3f4867bbe69a5ac7e45202",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 7 - Funnels & Destinations).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "landing-pages-full-breakdown", title: "Landing Pages - Full Breakdown", emoji: "🎬", desc: "11:26", video: true, videoUrl: "https://www.loom.com/share/d7f32ad752894d2e9e1a196d74bedb3c",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 7 - Funnels & Destinations).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "quiz-funnels", title: "Quiz Funnels", emoji: "🎬", desc: "5:00", video: true, videoUrl: "https://www.loom.com/share/1da7059fc5ab431a8707630691afee89",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 7 - Funnels & Destinations).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "coming-soon-confirmation-pages", title: "⏳ Coming Soon - Confirmation Pages", emoji: "📄", desc: "Coming soon",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 7 - Funnels & Destinations).</p><h2>Status</h2><p>Coming soon. No video published yet.</p>" },
    ],
  },
  {
    key: "module-8-testing-optimising-and-scaling", name: "Module 8 - Testing, Optimising & Scaling", emoji: "🧪",
    sops: [
      { slug: "how-testing-works-full-guide", title: "How Testing Works (Full Guide)", emoji: "🎬", desc: "10:38", video: true, videoUrl: "https://www.loom.com/share/2694987f81f54a8e82a731525833a44e",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 8 - Testing, Optimising & Scaling).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "an-introduction-to-the-triad-testing-method", title: "An Introduction To The Triad Testing Method", emoji: "🎬", desc: "12:06", video: true, videoUrl: "https://www.youtube.com/watch?v=LWewNNS_Q9o",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 8 - Testing, Optimising & Scaling).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "triad-testing-explained", title: "Triad Testing Explained", emoji: "🎬", desc: "8:43", video: true, videoUrl: "https://www.loom.com/share/c91a50a7605544b6a2b903ee9b3d7f61",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 8 - Testing, Optimising & Scaling).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "setting-up-our-triad-test", title: "Setting Up Our Triad Test", emoji: "🎬", desc: "14:04", video: true, videoUrl: "https://www.loom.com/share/b61f1c9d1be54de09e22866a8f1e22e6",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 8 - Testing, Optimising & Scaling).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "optimising-our-tests-14-day-checkin", title: "Optimising Our Tests (14 Day Checkin)", emoji: "🎬", desc: "8:49", video: true, videoUrl: "https://www.loom.com/share/0b15470152f14a8aa8f7b554af4b1460",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 8 - Testing, Optimising & Scaling).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
    ],
  },
  {
    key: "module-9-retargeting", name: "Module 9 - Retargeting", emoji: "🔁",
    sops: [
      { slug: "overview-to-meta-retargeting", title: "Overview to META retargeting", emoji: "🎬", desc: "17:57", video: true, videoUrl: "https://www.loom.com/share/882348e4c392492abfe3561101c34100",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 9 - Retargeting).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "budgets-for-retargeting-campaigns", title: "Budgets for Retargeting Campaigns", emoji: "🎬", desc: "5:25", video: true, videoUrl: "https://www.loom.com/share/ae66dc983dd54f4d93ad78a958c322aa",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 9 - Retargeting).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "creating-our-retargeting-ads", title: "Creating our retargeting ads", emoji: "🎬", desc: "9:26", video: true, videoUrl: "https://www.loom.com/share/9ad11545533642d483ff7e4981e209bd",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 9 - Retargeting).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "building-our-retargeting-campaign", title: "Building Our Retargeting Campaign", emoji: "🎬", desc: "21:05", video: true, videoUrl: "https://www.loom.com/share/da1d1333965542f0a85388feb95efa59",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 9 - Retargeting).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
    ],
  },
  {
    key: "module-10-reporting-and-tracking", name: "Module 10 - Reporting & Tracking", emoji: "📊",
    sops: [
      { slug: "understanding-meta-reports-inside-ads-manager", title: "Understanding META reports - inside ads manager", emoji: "🎬", desc: "6:19", video: true, videoUrl: "https://www.loom.com/share/77546a535a8c4040995a68da34516647",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 10 - Reporting & Tracking).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "understanding-meta-ads-report-google-sheet", title: "Understanding META ads report (google sheet)", emoji: "🎬", desc: "7:52", video: true, videoUrl: "https://www.loom.com/share/fa36fde8f11b451e99e487ddced096f9",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 10 - Reporting & Tracking).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "automating-daily-meta-stats", title: "Automating Daily Meta Stats", emoji: "🎬", desc: "5:46", video: true, videoUrl: "https://www.loom.com/share/597ee17ed81842f099fa0d9e4c3524de",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 10 - Reporting & Tracking).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "sending-leads-into-the-sheet", title: "Sending Leads Into The Sheet", emoji: "🎬", desc: "6:57", video: true, videoUrl: "https://www.loom.com/share/03d66ac872ce4b459efc74d551bbfe2d",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 10 - Reporting & Tracking).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
    ],
  },
  {
    key: "module-11-gohighlevel-lead-management", name: "Module 11 - GoHighLevel Lead Management", emoji: "📞",
    sops: [
      { slug: "how-high-level-snapshots-work", title: "How High Level Snapshots Work", emoji: "🎬", desc: "5:09", video: true, videoUrl: "https://www.loom.com/share/6b2ce4a3bff04fbf9f8c9b5db2dfaa50",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 11 - GoHighLevel Lead Management).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "customer-journey-ghl-snapshot-template", title: "Customer Journey (GHL Snapshot Template)", emoji: "🎬", desc: "11:08", video: true, videoUrl: "https://www.loom.com/share/a71e81c79b664471b6926cdda88ec5a6",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 11 - GoHighLevel Lead Management).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "snapshot-overview-walkthrough", title: "Snapshot Overview / Walkthrough", emoji: "🎬", desc: "18:47", video: true, videoUrl: "https://www.loom.com/share/f61a2e7cf6cd47a3a64453f5a6b495b6",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 11 - GoHighLevel Lead Management).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "how-to-import-the-snapshot", title: "How to Import the Snapshot", emoji: "🎬", desc: "3:59", video: true, videoUrl: "https://www.loom.com/share/0089df70c19440de913479f36d8efbf9",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 11 - GoHighLevel Lead Management).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "pushing-updates-to-client-sub-accounts", title: "Pushing Updates to Client Sub-accounts", emoji: "🎬", desc: "5:33", video: true, videoUrl: "https://www.loom.com/share/c5a6bb5073e443c7a4f6c78980321d84",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 11 - GoHighLevel Lead Management).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "custom-values-custom-fields-and-personalisation", title: "Custom Values, Custom Fields & Personalisation", emoji: "🎬", desc: "10:27", video: true, videoUrl: "https://www.loom.com/share/865499f7576d4f2e89a976c59a5f29b9",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 11 - GoHighLevel Lead Management).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "overview-to-automations", title: "Overview to Automations", emoji: "🎬", desc: "1:49", video: true, videoUrl: "https://www.loom.com/share/d1d3ff155ac4440baee20e32aee3cb75",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 11 - GoHighLevel Lead Management).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "pipelines-overview", title: "Pipelines Overview", emoji: "🎬", desc: "8:16", video: true, videoUrl: "https://www.loom.com/share/19c120d3449040ba955dd5f2ad82594e",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 11 - GoHighLevel Lead Management).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "automations-new-lead-and-follow-up-nurture", title: "Automations: ✉️ New Lead & Follow Up Nurture", emoji: "🎬", desc: "10:51", video: true, videoUrl: "https://www.loom.com/share/3dcaf91781c644a0978ee30509beceda",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 11 - GoHighLevel Lead Management).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "automations-attribution", title: "Automations: 🎯 Attribution", emoji: "🎬", desc: "1:06", video: true, videoUrl: "https://www.loom.com/share/c77d0c71b98b4a42988bf2474e7153f8",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 11 - GoHighLevel Lead Management).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "automations-appointment-booked-automations", title: "Automations: 📅 Appointment Booked Automations", emoji: "🎬", desc: "2:47", video: true, videoUrl: "https://www.loom.com/share/c9ec1aaeb4f04b07a9151b04912ab196",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 11 - GoHighLevel Lead Management).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "automations-reporting", title: "Automations: 📊 Reporting", emoji: "🎬", desc: "1:44", video: true, videoUrl: "https://www.loom.com/share/8e81465035104798a57d470c0d1fd178",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 11 - GoHighLevel Lead Management).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "automations-backend-workflows", title: "Automations: 🔧 Backend Workflows", emoji: "🎬", desc: "3:52", video: true, videoUrl: "https://www.loom.com/share/d1876d3ccd0047ca81c4ed0c24fff6bd",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 11 - GoHighLevel Lead Management).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "automations-alert-automations", title: "Automations: 🚨 Alert Automations", emoji: "🎬", desc: "6:59", video: true, videoUrl: "https://www.loom.com/share/985ac89206e342ac97d22104cba9e841",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 11 - GoHighLevel Lead Management).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "customisation-funnels", title: "Customisation: Funnels", emoji: "🎬", desc: "19:45", video: true, videoUrl: "https://www.loom.com/share/ea05bc72c59e4450a635ffc7eceecc16",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 11 - GoHighLevel Lead Management).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "survey-customisation-custom-fields", title: "Survey Customisation + Custom Fields", emoji: "🎬", desc: "7:46", video: true, videoUrl: "https://www.loom.com/share/279f4a87cbac491db4560851719bc2e1",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 11 - GoHighLevel Lead Management).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "customisation-automations", title: "Customisation: Automations", emoji: "🎬", desc: "17:49", video: true, videoUrl: "https://www.loom.com/share/361ca850187d4ac990a15a283d654387",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (Module 11 - GoHighLevel Lead Management).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
    ],
  },
  {
    key: "bonus-a-i-ad-creatives", name: "BONUS - A.I. Ad Creatives", emoji: "🤖",
    sops: [
      { slug: "introduction-to-a-i-creatives", title: "Introduction to A.I. Creatives", emoji: "🎬", desc: "4:41", video: true, videoUrl: "https://www.loom.com/share/4013d4432bfc43ee90557d7faa44fd06",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (BONUS - A.I. Ad Creatives).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "a-i-tools-overview", title: "A.I. Tools Overview", emoji: "🎬", desc: "7:44", video: true, videoUrl: "https://www.loom.com/share/c45a2cf0f31f42289352d5f1d5dd2fca",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (BONUS - A.I. Ad Creatives).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "product-placement-images", title: "Product Placement Images", emoji: "🎬", desc: "10:39", video: true, videoUrl: "https://www.loom.com/share/315d54b392124659a490281dc4223f7d",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (BONUS - A.I. Ad Creatives).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "a-i-image-editing", title: "A.I. Image Editing", emoji: "🎬", desc: "8:36", video: true, videoUrl: "https://www.loom.com/share/5fdcf7c59b514482a9ceda51eb529097",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (BONUS - A.I. Ad Creatives).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "personalised-people-based-image-ads", title: "Personalised People Based Image Ads", emoji: "🎬", desc: "14:50", video: true, videoUrl: "https://www.loom.com/share/f4688fd2561f430b967b3afdc84f66b6",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (BONUS - A.I. Ad Creatives).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "creating-a-i-b-roll-style-videos", title: "Creating A.I. B-roll style videos", emoji: "🎬", desc: "6:54", video: true, videoUrl: "https://www.loom.com/share/1b9ee6382224403abe0a65836c66bd50",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (BONUS - A.I. Ad Creatives).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "a-i-ugc-creating-avatars", title: "A.i. UGC - Creating Avatars", emoji: "🎬", desc: "3:37", video: true, videoUrl: "https://www.loom.com/share/9013b1ae831a41c2bbed8050cdc5ac89",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (BONUS - A.I. Ad Creatives).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "a-i-ugc-creating-our-voice", title: "A.i. UGC - Creating our voice", emoji: "🎬", desc: "3:27", video: true, videoUrl: "https://www.loom.com/share/a83013097e2a40c1a03dbe3cd59727f1",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (BONUS - A.I. Ad Creatives).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "a-i-ugc-generating-our-video-with-heygen", title: "A.i. UGC - Generating our video with HeyGen", emoji: "🎬", desc: "6:16", video: true, videoUrl: "https://www.loom.com/share/7cd8cca1766d47ef88b07d2603f39eca",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (BONUS - A.I. Ad Creatives).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "bonus-voice-cloning-with-a-i", title: "BONUS - Voice Cloning with A.I.", emoji: "🎬", desc: "4:56", video: true, videoUrl: "https://www.loom.com/share/f8118de54cb54083ad14807ca55f2ff3",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (BONUS - A.I. Ad Creatives).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
    ],
  },
  {
    key: "bonus-advanced-meta-strategies", name: "BONUS - Advanced META Strategies", emoji: "🧬",
    sops: [
      { slug: "utm-tracking-full-tutorial-and-live-setup", title: "UTM Tracking (Full tutorial & live setup)", emoji: "🎬", desc: "19:42", video: true, videoUrl: "https://www.loom.com/share/5c30a1f0c902404d90e20bb2b088cce5",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (BONUS - Advanced META Strategies).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
      { slug: "conversions-api-full-setup-tutorial-for-ghl", title: "Conversions API (Full Setup Tutorial - For GHL)", emoji: "🎬", desc: "13:02", video: true, videoUrl: "https://www.loom.com/share/bf6f719bb5f84cf58873eaca85121bce",
        body: "<h2>Source</h2><p>From <strong>Local Ads School</strong> (BONUS - Advanced META Strategies).</p><h2>Status</h2><p>Original training video above. Step-by-step SOP to be written from the video.</p>" },
    ],
  },
];

export function findSop(catKey: string, slug: string): { cat: SopCategory; sop: Sop } | null {
  const cat = SOP_CATEGORIES.find((c) => c.key === catKey);
  const sop = cat?.sops.find((s) => s.slug === slug);
  return cat && sop ? { cat, sop } : null;
}
